blank_issues_enabled: false
contact_links:
  - name: Cloudflare Workers ドキュメント
    url: https://developers.cloudflare.com/workers/
    about: Cloudflare Workers に関する公式ドキュメント
  - name: Cloudflare コミュニティ
    url: https://community.cloudflare.com/
    about: Cloudflare に関する質問や議論ができるコミュニティ